teatypes = [
    ["Green Tea", ["gt", ":tea:"]],
    ["Coffee", ["c"]],
    ["White Coffee", ["wc"]],
    ["White Coffee Instant", ["wci"]],
    ["White Coffee Espresso", ["wce"]],
    ["Tea w/o Much Milk", ["twom"]],
    ["Strong Black Tea", ["sbt"]],
    ["Strong Black Tea /w 2 Sugars", ["sbt2"]],
    ["Hot Chocolate", ["hc"]],
    ["Earl Grey", ["eg"]],
    ["White Tea", ["wt"]],
    ["White Tea /w 1 Sugar", ["wt1"]],
    ["White Tea /w 2 Sugars", ["wt2"]],
    ["White Tea /w Lots of Milk", ["wtlm"]],
    ["Black Coffee Instant", ["bci"]],
    ["Black Coffee Espresso", ["bce"]],
    ["Peppermint Tea", ["pt"]],
    ["White Earl Grey Tea", ["wegt"]],
    ["Black Americano", ["ba"]],
    ["Roooiboos Tea Black", ["rtb"]],
    ["Lemon Green Tea", ["lgt"]],
    ["Coffee Milkshake", ["cm"]],
]

peronitypes = [
    ["Peroni", ["p"]],
    ["Stowford", ["s"]],
    ["Small Stowford", ["ss"]],
    ["Guiness", ["g"]],
    ["Orange Juice", ["oj"]],
    ["Apple Juice", ["aj"]],
    ["Coke", ["c"]],
    ["Small Coke", ["sc"]],
    ["Diet Coke", ["dc"]],
    ["Small Diet Coke", ["sdc"]],
    ["Three Hop", ["3h"]],
    ["Sauvignon Blanc", ["sb"]],
    ["Small Sauvignon Blanc", ["ssb"]],
    ["Medium Sauvignon Blanc", ["msb"]],
    ["Large Sauvignon Blanc", ["lsb"]]
]
