teatypes = [
    ["Tea", ["t"]],
    ["Green Tea", ["gt"]]
    ["Coffee", ["c"]]
    ["Tea w/o Much Milk", ["twom"]]
    ["Strong Black Tea", ["sbt"]]
    ["Hot Chocolate", ["hc"]]
    ["Earl Grey", ["eg"]]
    ["Tea /w Milk", ["twm"]]
    ["White Tea", ["wt"]]
    ["White Tea /w 2 Sugars", ["wt2"]]
    ["White Tea /w Lots of Milk", ["wtlm"]]
    ["Black Coffee Instant", ["bci"]]
    ["Black Coffee Espresso", ["bce"]]
    ["Peppermint Tea", ["pt"]]
    ["White Earl Grey Tea", ["wegt"]]
    ["Black Americano", ["ba"]]
    ["Roooiboos Tea Black", ["rtb"]]
